# Generated by Django 4.2.1 on 2023-05-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunkosCategoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
                ('nombre', models.CharField(max_length=55, unique=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'funkos_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FunkosProducto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
                ('imagen', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=55, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('caja_personalizada', models.BooleanField(default=True)),
                ('detalles', models.CharField(blank=True, max_length=255, null=True)),
                ('personalizable', models.BooleanField(default=True)),
                ('tamaño_caja', models.CharField(default='16x12x9 cm', max_length=50)),
                ('tamaño_funko', models.CharField(default='13x6 cm', max_length=50)),
            ],
            options={
                'db_table': 'funkos_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('email_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=124, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
